# Generated by Django 5.2 on 2025-04-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_alter_message_author_delete_author'),
        ('user_management', '0002_remove_profile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
    ]
