# Generated by Django 5.0.3 on 2025-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='is_public',
        ),
        migrations.AddField(
            model_name='shelf',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
